# Menggunakan file docker compose versi 3.7
version: "3.7"

services:
  # Service 1 (item-db)
  item-db:
    # Menentukan image yang digunakan untuk service item-db
    image: mongo:3
    # Mengatur service agar selalu restart ketika berhenti
    restart: always
    # Volume app-db akan digunakan untuk penyimpanan database
    volumes:
      - app-db:data/db
    ports:
      - 27017:27017
  # Service 2 (item-app)
  item-app:
    # Menentukan image yang digunakan untuk service item-app
    image: ariqhwari/item-app:v1
    # Mengatur service agar selalu restart ketika berhenti
    restart: always
    # Mengatur port 80 yang akan diarahkan ke port 8080 pada container
    ports:
      - 80:8080
    # Service item-app akan bergantung pada item-db
    depends_on:
      - item-db

# Mengatur volume dengan nama app-db
volumes:
  app-db:
